---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-application-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: ghcr.io/howtodie123/backend:main-43cbc1928e2c6d203c7b4fb3250e54b23b8e5287
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app/BOOT-INF/classes/application.properties
              subPath: application.properties
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            # initialDelaySeconds: 15
            # periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            # initialDelaySeconds: 15
            # periodSeconds: 10
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      volumes:
        - name: config-volume
          secret:
            secretName: springboot-secrets

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
  type: NodePort