apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: springboot-secrets
  namespace: default
spec:
  refreshInterval: "300s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: springboot-secrets
    template:
      engineVersion: v2
      data:
        application.yaml: |
          spring:
            datasource:
              url: {{ .spring_datasource_url }}
              username: {{ .spring_datasource_username }}
              password: {{ .spring_datasource_password }}
            jpa:
              hibernate:
                ddl-auto: update
              show-sql: true
            mail:
              username: {{ .spring_mail_username }}
              password: {{ .spring_mail_password }}
  data:
  - secretKey: spring_datasource_url
    remoteRef:
      key: springboot-secrets
      property: database_url

  - secretKey: spring_datasource_username
    remoteRef:
      key: springboot-secrets
      property: database_username

  - secretKey: spring_datasource_password
    remoteRef:
      key: springboot-secrets
      property: database_password

  - secretKey: spring_mail_username
    remoteRef:
      key: springboot-secrets
      property: email_username

  - secretKey: spring_mail_password
    remoteRef:
      key: springboot-secrets
      property: email_password