apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: springboot-secrets
#  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: springboot-secret
    template:
      engineVersion: v2
      data:
        credentials: |
          spring_datasource_url="{{ .spring_datasource_url }}"
          spring_datasource_username="{{ .spring_datasource_username }}"
          spring_datasource_password="{{ .spring_datasource_password }}"
          spring_mail_username="{{ .spring_mail_username }}"
          spring_mail_password="{{ .spring_mail_password }}"
  data:
  - secretKey: spring_datasource_url
    remoteRef:
      key: springboot_credentials
      property: database_url

  - secretKey: spring_datasource_username
    remoteRef:
      key: springboot_credentials
      property: database_username

  - secretKey: spring_datasource_password
    remoteRef:
      key: springboot_credentials
      property: database_password

  - secretKey: spring_mail_username
    remoteRef:
      key: springboot_credentials
      property: email_username

  - secretKey: spring_mail_password
    remoteRef:
      key: springboot_credentials
      property: email_password