apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: springboot-secrets
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: springboot-secrets
    template:
      engineVersion: v2
      data:
        application.properties: |
          spring.datasource.url="{{ .spring_datasource_url }}"
          spring.datasource.username="{{ .spring_datasource_username }}"
          spring.datasource_password="{{ .spring_datasource_password }}"
          spring.mail.username="{{ .spring_mail_username }}"
          spring.mail.password="{{ .spring_mail_password }}"
  data:
  - secretKey: spring_datasource_url
    remoteRef:
      key: springboot-secrets
      property: database_url

  - secretKey: spring_datasource_username
    remoteRef:
      key: springboot-secrets
      property: database_username

  - secretKey: spring_datasource_password
    remoteRef:
      key: springboot-secrets
      property: database_password

  - secretKey: spring_mail_username
    remoteRef:
      key: springboot-secrets
      property: email_username

  - secretKey: spring_mail_password
    remoteRef:
      key: springboot-secrets
      property: email_password