---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-application-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: ghcr.io/howtodie123/backend:main-fec7dd860ea3a237c2ac43fcdf297fab87d0f7c9
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: spring.datasource.password
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: spring.mail.username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: spring.mail.password
            - name: APP_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: app.jwtSecret
            - name: APP_JWTEXPIRATIONMS
              valueFrom:
                secretKeyRef:
                  name: springboot-secrets
                  key: app.jwtExpirationMs

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            # initialDelaySeconds: 15
            # periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
              initialDelaySeconds: 20
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
      # volumes:
      #   - name: config-volume
      #     secret:
      #       secretName: springboot-secrets

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
  type: NodePort