apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: springboot-secrets
  namespace: default
spec:
  refreshInterval: "300s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: springboot-secrets
    template:
      engineVersion: v2
      # data:
      #   application.properties: |
      #     spring.datasource.url="{{.spring_datasource_url }}"
      #     spring.datasource.username="{{.spring_datasource_username }}"
      #     spring.datasource.password="{{.spring_datasource_password }}"
      #     spring.mail.username="{{.spring_mail_username }}"
      #     spring.mail.password="{{.spring_mail_password }}"
  data:
  - secretKey: spring.datasource.url
    remoteRef:
      key: springboot-secrets
      property: database_url

  - secretKey: spring.datasource.username
    remoteRef:
      key: springboot-secrets
      property: database_username

  - secretKey: spring.datasource.password
    remoteRef:
      key: springboot-secrets
      property: database_password

  - secretKey: spring.mail.username
    remoteRef:
      key: springboot-secrets
      property: email_username

  - secretKey: spring.mail.password
    remoteRef:
      key: springboot-secrets
      property: email_password

  - secretKey: app.jwtExpirationMs
    remoteRef:
      key: springboot-secrets
      property: jwt_expiration

  - secretKey: app.jwtSecret
    remoteRef:
      key: springboot-secrets
      property: jwt_secret